# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - groupwhatsapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies for backend
        working-directory: backend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install dependencies for frontend
        working-directory: frontend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present -- --passWithNoTests

      - name: Zip backend artifact for deployment
        run: zip -r release-backend.zip backend/*

      - name: Zip frontend artifact for deployment
        run: zip -r release-frontend.zip frontend/*

      - name: Upload artifacts for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            release-backend.zip
            release-frontend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip backend artifact for deployment
        run: unzip -o release-backend.zip -d release-backend

      - name: Unzip frontend artifact for deployment
        run: unzip -o release-frontend.zip -d release-frontend
      
      - name: Set up Node.js version for deployment
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install PM2
        run: npm install -g pm2

      - name: Install MongoDB driver
        run: npm install mongodb
      
      - name: Install dependencies for backend
        working-directory: release-backend/backend
        run: npm install

      - name: Start backend server
        working-directory: release-backend/backend
        run: |
          pm2 start server.js
      
      - name: 'Deploy backend to Azure Web App'
        id: deploy-backend-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'groupwhatsapp'
          slot-name: 'Production'
          package: ./release-backend/backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AAAF6CDE20D44FBEA0C710047C38524B }}

      - name: Install dependencies for frontend
        working-directory: release-frontend/frontend
        run: npm install
  
      - name: Install serve for serving static files
        run: npm install -g serve
  
      - name: Serve frontend
        working-directory: release-frontend/frontend
        run: pm2 serve build --name frontend

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'groupwhatsapp'
          slot-name: 'Production'
          package: ./release-frontend/frontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AAAF6CDE20D44FBEA0C710047C38524B }}
